language: python
python:
  - '2.7'
before_install:
  - sudo apt-get update
  - sudo apt-get install python-pip
install: sudo apt-get install python-numpy
script: nosetests pieMath_test.py
notifications:
  email:
    recipients:
      - aravind.kumaraguru@gmail.com
      - aravindkumaraguru@pioneers.berkeley.edu
    on_success: change  # if CI succeeds, only sends notification if build status changes
    on_failure: always  # if CI fails, always sends notification
